name: air_pollution
description: provide_air_pollution

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # use for phone database
  hive: ^2.2.2
  hive_flutter: ^1.1.0

  # use for http request
  dio: ^4.0.6

  # use for api access key
  flutter_dotenv: ^5.0.2

  # use for animation in stless
  simple_animations: ^4.1.0
  supercharged: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # use for hive when develop
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

flutter:

  uses-material-design: true

  assets:
    - asset/img/
    - .env

  fonts:
    - family: sunflower
      fonts:
        - asset: asset/fonts/Sunflower-Bold.ttf
          weight: 700
        - asset: asset/fonts/Sunflower-Medium.ttf
          weight: 500
        - asset: asset/fonts/Sunflower-Light.ttf
          weight: 300
